module.exports = {
  UID: 'uid',
  DISPLAY_NAME: 'displayName',
  EMAIL: 'email',
  PHOTO_URL: 'photoURL',
  MEMBERSHIP_EXPIRES_AT: 'membershipExpiresAt',
  SUBSCRIBER_IS_ACTIVE: 'isActive',
  ARRAY_KEY: 'values',
  IS_MEMBER: 'isMember',
  SUBSCRIBERS_ARRAY_KEY: 'values',
  ADDRESS1: 'address1',
  ADDRESS2: 'address2',
  CITY: 'city',
  ZIP: 'zip',
  STATE: 'state',
  PHONE: 'phone',
  DATE_OF_BIRTH: 'dateOfBirth',
  GENDER: 'gender',
  GRAVATAR_URL: 'gravatarUrl',

  ONLY_ME: 'ONLY_ME',
  MEMBERS: 'MEMBERS',
}