version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            npm install
            cd functions
            npm install
            cd ../lambda
            npm install
            zip -r ../public/lambda.zip .
      - run:
          name: Build Application
          command: npm run build
      - run:
          name: Install Firebase Tools
          command: npm install --prefix=./firebase-deploy firebase-tools
      - run:
          name: Deploy to Firebase
          command: ./firebase-deploy/node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get install -y python-pip libyaml-dev python-dev jq
            sudo pip install awscli
      - run:
          name: Push to S3
          command: aws s3 sync build s3://www.belmontrunners.com --delete
