version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: cimg/node:16.14.2
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            npm install
            cd functions
            npm install
      - run:
          name: Build Application
          command: npm run build
      - run:
          name: Install Firebase Tools
          command: npm install --prefix=./firebase-deploy firebase-tools
      - run:
          name: Deploy to Firebase Hosting
          command: ./firebase-deploy/node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN --force --only hosting
      - run:
          name: Deploy to Firebase Functions
          command: ./firebase-deploy/node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN --force --only functions
