export const UID = 'uid'
export const DISPLAY_NAME = 'displayName'
export const EMAIL = 'email'
export const PHOTO_URL = 'photoURL'
export const ARRAY_KEY = 'values'
export const SUBSCRIBERS_ARRAY_KEY = 'values'
export const ADDRESS1 = 'address1'
export const ADDRESS2 = 'address2'
export const CITY = 'city'
export const ZIP = 'zip'
export const STATE = 'state'
export const PHONE = 'phone'
export const DATE_OF_BIRTH = 'dateOfBirth'
export const GENDER = 'gender'
export const GRAVATAR_URL = 'gravatarUrl'

export const ONLY_ME = 'ONLY_ME'
export const MEMBERS = 'MEMBERS'
